const exerciseLibrary = [
	{
		id: 1,
		name: "Barbell Squat",
		category: "strength",
		primaryMuscle: "Quadriceps",
		difficulty: "Intermediate",
		image: "https://images.pexels.com/photos/4164769/pexels-photo-4164769.jpeg?auto=compress&cs=tinysrgb&w=300",
		link: "https://www.muscleandstrength.com/exercises/squat.html",
	},
	{
		id: 2,
		name: "Bench Press",
		category: "strength",
		primaryMuscle: "Chest",
		difficulty: "Intermediate",
		image: "https://images.pexels.com/photos/2204196/pexels-photo-2204196.jpeg?auto=compress&cs=tinysrgb&w=300",
		link: "https://www.muscleandstrength.com/exercises/dumbbell-bench-press.html",
	},
	{
		id: 3,
		name: "Deadlift",
		category: "strength",
		primaryMuscle: "Back",
		difficulty: "Advanced",
		image: "https://images.pexels.com/photos/1229356/pexels-photo-1229356.jpeg?auto=compress&cs=tinysrgb&w=300",
		link: "https://www.muscleandstrength.com/exercises/stiff-leg-deadlift-aka-romanian-deadlift.html",
	},
	{
		id: 4,
		name: "Pull-ups",
		category: "strength",
		primaryMuscle: "Back",
		difficulty: "Intermediate",
		image: "https://images.pexels.com/photos/4162504/pexels-photo-4162504.jpeg?auto=compress&cs=tinysrgb&w=300",
		link: "https://www.muscleandstrength.com/exercises/wide-grip-pull-up.html",
	},
	{
		id: 5,
		name: "Running",
		category: "cardio",
		primaryMuscle: "Full Body",
		difficulty: "Beginner",
		image: "https://images.pexels.com/photos/3760278/pexels-photo-3760278.jpeg?auto=compress&cs=tinysrgb&w=300",
		link: "https://www.muscleandstrength.com/exercises/wide-grip-pull-up.html",
	},
	{
		id: 6,
		name: "Crunches",
		category: "hiit",
		primaryMuscle: "Full Body",
		difficulty: "Intermediate",
		image: "https://images.pexels.com/photos/6456155/pexels-photo-6456155.jpeg?auto=compress&cs=tinysrgb&w=300",
		link: "https://www.muscleandstrength.com/exercises/sit-up.html",
	},
];
export default exerciseLibrary;
