const upcomingWorkouts = [
	{
		id: 1,
		title: "Chest & Triceps",
		date: "2023-06-22T10:00:00",
		duration: 60,
		trainer: "Jane Smith",
		location: "Main Gym Floor",
		category: "chest",
	},
	{
		id: 2,
		title: "Back & Biceps",
		date: "2023-06-23T11:00:00",
		duration: 60,
		trainer: "Mike Brown",
		location: "Main Gym Floor",
		category: "back",
	},
	{
		id: 3,
		title: "Leg Day",
		date: "2023-06-24T16:30:00",
		duration: 70,
		trainer: "Sarah Davis",
		location: "Studio 1",
		category: "legs",
	},
	{
		id: 4,
		title: "HIIT Cardio Session",
		date: "2023-06-25T09:00:00",
		duration: 45,
		trainer: "Emily Johnson",
		location: "Studio 2",
		category: "cardio",
	},
	{
		id: 5,
		title: "Core & Abs",
		date: "2023-06-26T12:00:00",
		duration: 50,
		trainer: "David Lee",
		location: "Studio 1",
		category: "abs",
	},
	{
		id: 6,
		title: "Shoulder & Arms",
		date: "2023-06-27T14:00:00",
		duration: 60,
		trainer: "Anna White",
		location: "Main Gym Floor",
		category: "shoulders",
	},
	{
		id: 7,
		title: "Yoga Flow",
		date: "2023-06-28T09:00:00",
		duration: 75,
		trainer: "Sarah Davis",
		location: "Yoga Studio",
		category: "yoga",
	},
];

export default upcomingWorkouts;
